# Generated by Django 4.0.1 on 2022-01-27 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiltdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='machine',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='tiltdb.venue'),
        ),
    ]
