# Generated by Django 4.0.1 on 2022-01-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiltdb', '0004_alter_machine_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='tiltdb.venue'),
        ),
    ]
