# Generated by Django 4.0.1 on 2022-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiltdb', '0005_alter_machine_price_alter_machine_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='machine',
            field=models.CharField(default='blank', max_length=258, null=True),
        ),
    ]
